version: '3.8'

services:  
  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    ports: 
      - "8081:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=172.17.0.1:9092

  # Zookeeper: required by Kafka
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - './zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # Kafka itself
  kafka:
    image: 'bitnami/kafka:2'
    container_name: kafka
    ports:
      - '9092:9092'
    volumes:
      - './kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=172.17.0.1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      # - KAFKA_ADVERTISED_HOST_NAME=localhost
    depends_on:
      - zookeeper